// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';

import { defineConfig } from 'prisma/config';

const backendPackagePath = "./packages/backend-api";

export default defineConfig({
  schema: `${backendPackagePath}/prisma/schema.prisma`,
  migrations: {
    path: `${backendPackagePath}/prisma/migrations`,
    seed: `npm --prefix packages/backend-api run seed`
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
