// Resolves the build's version stamp (semver + git short hash) once at
// dev/build start and writes it into a generated, gitignored module that both
// apps import via `@shared/generated/version`. Baking it at build time — rather
// than shelling out to git at runtime — keeps the value stable regardless of
// the deployed process's cwd or whether `.git` is present at runtime.
//
// Wired in as a `predev`/`prebuild` step for both packages, so every dev and
// build path regenerates it and it can never go stale.

import { execFileSync } from 'child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, '..');
const outFile = path.join(
  repoRoot,
  'packages',
  'shared',
  'src',
  'generated',
  'version.ts',
);

function git(...args) {
  try {
    return execFileSync('git', args, {
      cwd: repoRoot,
      encoding: 'utf8',
    }).trim();
  } catch {
    return '';
  }
}

function readAppVersion() {
  try {
    const pkgPath = path.join(repoRoot, 'packages', 'shared', 'package.json');
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
    return pkg.version ?? '0.0.0';
  } catch {
    return '0.0.0';
  }
}

const appVersion = readAppVersion();
const commit = git('rev-parse', '--short', 'HEAD') || 'unknown';
const isDirty = git('status', '--porcelain').length > 0;
const buildTime = new Date().toISOString();
// The git hash is the real "what's running" signal — the semver is vestigial
// (private, unpublished workspaces) so it stays out of the human-facing label.
// APP_VERSION is still exported below in case it's ever wanted.
const label = `${commit}${isDirty ? '-dirty' : ''}`;

const contents = `// AUTO-GENERATED by scripts/generate-version.mjs at dev/build start.
// Do not edit and do not commit — this file is gitignored.
export const APP_VERSION = ${JSON.stringify(appVersion)};
export const GIT_COMMIT = ${JSON.stringify(commit)};
export const GIT_DIRTY = ${JSON.stringify(isDirty)};
export const BUILD_TIME = ${JSON.stringify(buildTime)};
export const VERSION_LABEL = ${JSON.stringify(label)};
`;

mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(outFile, contents);

console.log(`generate-version: ${label}`);
